# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

    # Constantes de configuration pour l'utilisation de l'API Jawbone
    app.jawbone.client_id: 'NVXBLmwjIag'
    app.jawbone.client_secret: '89cd42ffbe3f8df0306b31d9728219179d3cc4af'

    app.jawbone.scopes: 
        - "basic_read"
        - "extended_read"
        - "location_read"
        - "friends_read"
        - "mood_read"
        - "mood_write"
        - "move_read"
        - "move_write"
        - "sleep_read"
        - "sleep_write"
        - "meal_read"
        - "meal_write"
        - "weight_read"
        - "weight_write"
        - "cardiac_read"
        - "cardiac_write"
        - "generic_event_read"
        - "generic_event_write"

services:
    fos_user.doctrine_registry:
            alias: doctrine

    app.ukandoit:
            class: AppBundle\Services\Ukandoit\Ukandoit

    app.withings:
        class: AppBundle\Services\Devices\Withings\Withings

    app.jawbone:
        class: AppBundle\Services\Devices\Jawbone\Jawbone
        arguments: ['%app.jawbone.client_id%', '%app.jawbone.client_secret%', '%app.jawbone.scopes%', @router]

    app.form.registration:
        class: UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: UserBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }