# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

    # Constantes de configuration pour l'utilisation de l'API Withings
    BASE_URL: https://oauth.withings.com/account/
    URLWSAPI: http://wbsapi.withings.net/
    CALLBACK_URL: http://localhost:8080/ukandoit/withings/ #http://www.ukandoit.fr/withings/callback [à changer avec l'url de notre site]
    OAUTH_CONSUMER_KEY: 31ec099bddfee6fb7b16d5bc502e8b5bcbbddf0de39346316427f8f25fd
    OAUTH_CONSUMER_SECRET: 0d50d732c6655ee07d727ffbc336751d8b3b7c298e32167d945589692e5e9b16
    LOG_BASE_PATH: /var/log/withings

    # Constantes de configuration pour l'utilisation de l'API Jawbone

    app.jawbone.client_id: '7E2uPrNbR3I'
    app.jawbone.client_secret: '8f662520d8d2619c7855691053571c24bc82f4c1'
    app.jawbone.redirect_uri: 'http://localhost:443/web/app_dev.php/jawbone/token'

    app.jawbone.scopes: 
        - "basic_read"
        - "extended_read"
        - "location_read"
        - "friends_read"
        - "mood_read"
        - "mood_write"
        - "move_read"
        - "move_write"
        - "sleep_read"
        - "sleep_write"
        - "meal_read"
        - "meal_write"
        - "weight_read"
        - "weight_write"
        - "cardiac_read"
        - "cardiac_write"
        - "generic_event_read"
        - "generic_event_write"

services:

    app.withings:
        class: AppBundle\Services\Devices\Withings\Withings

    app.jawbone:
        class: AppBundle\Services\Devices\Jawbone\Jawbone
        arguments: ['%app.jawbone.client_id%', '%app.jawbone.client_secret%', '%app.jawbone.redirect_uri%', '%app.jawbone.scopes%']

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }