# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    withings.oauth:
        class: AppBundle\Services\Withings\OAuth

    withings.log:
        class: AppBundle\Services\Withings\Log

    withings.wbsapi:
        class: AppBundle\Services\Withings\WBSApi
